from bson import ObjectId
from pydantic import BaseModel, Field
from datetime import date, time, datetime
from typing import Optional

class BookingSchema(BaseModel):
    # id: Optional[str] = None  # Auto-generated by MongoDB
    service_id: str
    user_id: str
    booking_type: int
    booking_date: str
    booking_start_time: time
    booking_end_time: time
    booking_source: int
    status: int
    paid_status: bool
    created_on_date: Optional[date] = None
    created_on_time: Optional[time] = None
    created_by: Optional[str]

    class Config:
        json_encoders = {
            ObjectId: str,  # Ensure ObjectId is converted to string in JSON
            datetime: lambda v: v.isoformat(),
        }
    #
    # def to_dict(self):
    #     """Converts the model instance to a dictionary."""
    #     return self.model_dump(by_alias=True)
