from fastapi import APIRouter
from booking_manager.routes.booking_router import booking_router
from booking_manager.routes.services_router import services_router

booking_manager_router=APIRouter()

booking_manager_router.include_router(booking_router)
booking_manager_router.include_router(services_router)